# Generated by Django 4.1.4 on 2023-01-08 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeyssareCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_cfa_dispo', models.FloatField()),
                ('montant_fg_dispo', models.FloatField()),
                ('montant_depencee', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeyssareMembres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=40)),
                ('id_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VersementLeyssare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=40)),
                ('montant_cfa', models.FloatField(blank=True, null=True)),
                ('montant_fg', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionPeriodique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('a_versee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BleyApp.versementleyssare')),
            ],
        ),
    ]
