# Generated by Django 4.1.4 on 2023-01-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BleyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeyssareDepenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_de_depense', models.TextField()),
                ('montant_cfa', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
