# Generated by Django 4.1.4 on 2023-01-14 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BleyApp', '0002_leyssaredepenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leyssaredepenses',
            old_name='montant_cfa',
            new_name='montant_depensee',
        ),
    ]
